artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://raw.githubusercontent.com/krishnaik06/mlops/main/wine_quality.csv
  local_data_file: artifacts/data_ingestion/wine_quality.csv

data_validation:
  root_dir: artifacts/data_validation
  local_data_file: artifacts/data_ingestion/wine_quality.csv
  STATUS_FILE: artifacts/data_validation/status.txt  

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/wine_quality.csv